#------------------------------------------------------------------------------
# UniVex Engine (UVE) — Proprietary Game Engine
# Copyright (c) 2026 UniVex Studios. All Rights Reserved.
# Unauthorized copying, modification, distribution, or use of this code
# in whole or in part is strictly prohibited without express written
# permission from UniVex Studios.
# Violators will be prosecuted to the fullest extent of the law.
#------------------------------------------------------------------------------

add_subdirectory(platform)
add_subdirectory(debug)
add_subdirectory(utilities)
add_subdirectory(events)
add_subdirectory(memory)
add_subdirectory(threading)
add_subdirectory(core)
add_subdirectory(app)
