# Copyright (c) 2026 UniVex Studios. All Rights Reserved.


add_subdirectory(platform)
add_subdirectory(debug)
add_subdirectory(utilities)
add_subdirectory(events)
add_subdirectory(memory)
add_subdirectory(threading)
add_subdirectory(math)
add_subdirectory(input)
add_subdirectory(commandline)
add_subdirectory(config)
add_subdirectory(asset)
add_subdirectory(scene)
add_subdirectory(physics)
add_subdirectory(window)
add_subdirectory(render)
add_subdirectory(audio)
add_subdirectory(save)
add_subdirectory(core)
add_subdirectory(editor)
add_subdirectory(project_check)
add_subdirectory(app)
